services:
  optiserver:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    image: optiserver:dev
    volumes:
      - ../..:/app
    environment:
      ALLOWED_HOSTS: "*"
      OSRM_BASE_URL: "http://host.docker.internal:5000"
    ports:
      - 8010:8000
