services:
  optiserver:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    image: optiserver:dev
    volumes:
      - ../..:/app
    environment:
      ALLOWED_HOSTS: "*"
    ports:
      - 8010:8000
