from django.conf import settings

MISS_PENALTY = settings.OPTIRIDER_SETTINGS["CONSTANTS"]["MISS_PENALTY"]
WAIT_TIME_AT_WAREHOUSE = int(
    settings.OPTIRIDER_SETTINGS["CONSTANTS"]["WAIT_TIME_AT_WAREHOUSE"].total_seconds()
)
LATE_DELIVERY_PENALTY_PER_SEC = settings.OPTIRIDER_SETTINGS["CONSTANTS"][
    "LATE_DELIVERY_PENALTY_PER_SEC"
]
GLOBAL_START_TIME = int(
    settings.OPTIRIDER_SETTINGS["CONSTANTS"]["GLOBAL_START_TIME"].total_seconds()
)
GLOBAL_END_TIME = int(
    settings.OPTIRIDER_SETTINGS["CONSTANTS"]["GLOBAL_END_TIME"].total_seconds()
)
MAX_TRIP_TIME = int(
    settings.OPTIRIDER_SETTINGS["CONSTANTS"]["MAX_TRIP_TIME"].total_seconds()
)
DEFAULT_TIME_LIMIT = int(
    settings.OPTIRIDER_SETTINGS["CONSTANTS"]["DEFAULT_TIME_LIMIT"].total_seconds()
)

CAPACITY_DIMENSION_NAME = "Free Space"
TIME_DIMENSION_NAME = "Time"
